# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-14 14:21
from __future__ import unicode_literals

import collab_profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import private_media.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, storage=private_media.storages.PrivateMediaStorage(), upload_to=collab_profile.models.file_upload_path)),
                ('organization', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='self description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
